### ISSUE TITLE
Error "Unexpected double format" on some machines

### ISSUE THREAD

**Issue by SemenMartynov** [squeaky-pl/portable-pypy#56]
After
```
docker run --rm `ABI=64 ./runopt.sh` portable-pypy ./build_deps
```

I see

```
+ make -j4
echo @`sh  cflags "optimize='-O2'" opmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
@cc -c -DPERL_CORE -D__USE_XOPEN2K8 -I/opt/prefix/include -I/opt/prefix/include/ncurses -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
In file included from op.c:103:0:
perl.h:6978:6: error: #error "Unexpected double format"
 #    error "Unexpected double format"
      ^~~~~
perl.h:7177:6: error: #error "Unexpected double format"
 #    error "Unexpected double format"
      ^~~~~
feature.h:151: confused by earlier errors, bailing out
make: *** [opmini.o] Error 1
```

**Comment by SemenMartynov** [comment]
Hmm... I'm a bit confused...
I meet this issue on Ubuntu 16.04, but on CentOS 7.3 everything works like a charm!
I thought there shouldn't be different because of docker.

**Comment by squeaky-pl** [comment]
This is entirely possible since the volumes are mounted inside your host operating system. Something about how you configured your file system or particular file system can lead to this problem.

**Comment by SemenMartynov** [comment]
I can see, that it doesn't related with ubuntu...

I have two hosts and on the first build goes well and on another it ends with an error. The difference in flags!

```
user@bad$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

```
echo @`sh  cflags "optimize='-O2'" opmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
@cc -c -DPERL_CORE -D__USE_XOPEN2K8 -I/opt/prefix/include -I/opt/prefix/include/ncurses -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
In file included from op.c:103:0:
perl.h:6978:6: error: #error "Unexpected double format"
 #    error "Unexpected double format"
      ^~~~~
perl.h:7177:6: error: #error "Unexpected double format"
 #    error "Unexpected double format"
      ^~~~~
feature.h:151: confused by earlier errors, bailing out
make: *** [opmini.o] Error 1
```
~
```
user@good$$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```


```
echo @`sh  cflags "optimize='-O2'" opmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
@cc -c -DPERL_CORE -D__USE_XOPEN2K8 -I/opt/prefix/include -I/opt/prefix/include/ncurses -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c89 -O2 -Wall -Werror=declaration-after-statement -Wextra -Wc++-compat -Wwrite-strings -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
```

**Comment by SemenMartynov** [comment]
I noticed another feature on the bad host

```
[root@3be89043a175 perl-5.24.1]# ./configure.gnu --prefix=/opt/prefix
try.c: In function 'main':
try.c:9:2: internal compiler error: Illegal instruction
  {4294967303.15, 4294967303ULL},
  ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

**Comment by SemenMartynov** [comment]
I believe I see where issue is, but don't know how to fix it:
```
Checking the kind of long doubles you have...
Cannot figure out your long double.
```

**Comment by SemenMartynov** [comment]
So here's what I noticed.
If I throw out custom gcc 7.1.0 (https://github.com/squeaky-pl/centos-devtools/) from the `Dockerfile`
and use the standard gcc 4.4.7, everything works quite well on all of my servers and distributives.
@squeaky-pl, please pay attention.

**Comment by SemenMartynov** [comment]
I'm not sure it's related to the previous problem, but now I'm faced with this:
```
--2017-10-28 08:53:46--  https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz
Resolving pypi.python.org... 151.101.36.223, 2a04:4e42:9::223
Connecting to pypi.python.org|151.101.36.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 231163 (226K) [application/octet-stream]
Saving to: `STDOUT'

     0K .......... .......... .......... .......... .......... 22%  502K 0s
    50K .......... .......... .......... .......... .......... 44% 1.37M 0s
   100K .......... .......... .......... .......... .......... 66% 2.48M 0s
   150K .......... .......... .......... .......... .......... 88% 5.95M 0s
   200K .......... .......... .....                           100% 1.70M=0.2s

2017-10-28 08:53:46 (1.24 MB/s) - written to stdout [231163/231163]

patching file rpython/translator/platform/linux.py
Hunk #1 succeeded at 29 (offset 3 lines).
Traceback (most recent call last):
  File "rpython/bin/rpython", line 13, in <module>
    from rpython.translator.goal.translate import main
  File "/src/pypy/rpython/translator/goal/translate.py", line 13, in <module>
    from rpython.config.translationoption import (get_combined_translation_config,
  File "/src/pypy/rpython/config/translationoption.py", line 7, in <module>
    from rpython.translator.platform import platform as compiler
  File "/src/pypy/rpython/translator/platform/__init__.py", line 5, in <module>
    from rpython.tool.runsubprocess import run_subprocess as _run_subprocess
  File "/src/pypy/rpython/tool/runsubprocess.py", line 11, in <module>
    PY2 = (sys.version_info.major == 2)
AttributeError: 'tuple' object has no attribute 'major'
```

**Comment by SemenMartynov** [comment]
I'm not sure it's related to the previous problem, but now I'm faced with this:
--2017-10-28 08:53:46--  https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz
```
Resolving pypi.python.org... 151.101.36.223, 2a04:4e42:9::223
Connecting to pypi.python.org|151.101.36.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 231163 (226K) [application/octet-stream]
Saving to: `STDOUT'

     0K .......... .......... .......... .......... .......... 22%  502K 0s
    50K .......... .......... .......... .......... .......... 44% 1.37M 0s
   100K .......... .......... .......... .......... .......... 66% 2.48M 0s
   150K .......... .......... .......... .......... .......... 88% 5.95M 0s
   200K .......... .......... .....                           100% 1.70M=0.2s

2017-10-28 08:53:46 (1.24 MB/s) - written to stdout [231163/231163]

patching file rpython/translator/platform/linux.py
Hunk #1 succeeded at 29 (offset 3 lines).
Traceback (most recent call last):
  File "rpython/bin/rpython", line 13, in <module>
    from rpython.translator.goal.translate import main
  File "/src/pypy/rpython/translator/goal/translate.py", line 13, in <module>
    from rpython.config.translationoption import (get_combined_translation_config,
  File "/src/pypy/rpython/config/translationoption.py", line 7, in <module>
    from rpython.translator.platform import platform as compiler
  File "/src/pypy/rpython/translator/platform/__init__.py", line 5, in <module>
    from rpython.tool.runsubprocess import run_subprocess as _run_subprocess
  File "/src/pypy/rpython/tool/runsubprocess.py", line 11, in <module>
    PY2 = (sys.version_info.major == 2)
AttributeError: 'tuple' object has no attribute 'major'
```

**Comment by desowin** [comment]
I noticed that "Cannot figure out you long double" happens when I run docker inside Linux running in VirtualBox. When Linux runs directly, then I noticed the internal compiler error.

I managed to build perl using 5bd0b05632d41618373afb99b61a5a7389cb6011 with modified env.list to contain /opt/devtools-7.1/bin instead of /opt/devtools-7.2/bin

**Comment by SemenMartynov** [comment]
Yes, I also can not get build with 7.2.

As for 7.1 -- on some machines it works, but for some it does not, and I could not detect the dependence. I have an observation that the autotool checks the CPU for the support long double, and not always find it.

And one more detail - if I build on the native host (i.e. without Docker) the build always goes well!..

So the issue is somewhere between toolchain and the Docker.

**Comment by SemenMartynov** [comment]
Finlay I found the issue!
`This usually means the gmp or mpfr library you are using is compiled not for the machine you are using and compiled for a new processor.`
So, it is in tool-chain...
